### ISSUE TITLE
CMake build

### ISSUE THREAD

**Issue by redtide** [franko/lua#1]
After being stuck with Meson while trying to create an AppVeyor macOS Lite XL universal binary build, I decided to write a CMake configuration, so I ended up with one for this repository as well. 
I wonder if you can make an use of it here, regardless of whether it will be used for Lite XL or not.

**Comment by franko** [comment]
@redtide I see this is an old issues you are closing now. I missed this issue when it was originally posted but just to let you know I am fine to integrate a cmake configuration for Lua if you still think it could be useful.
